app:
    resource: "@AppBundle/Controller/"
    type:     annotation

projects:
    type:     rest
    resource: AppBundle\Controller\ProjectController

users:
    type:     rest
    resource: AppBundle\Controller\UserController

conterparts:
    type:     rest
    resource: AppBundle\Controller\ConterpartController